package cooksystem.server.services.Implementations;

import cooksystem.server.dtos.*;
import cooksystem.server.entities.User;
import cooksystem.server.entities.embaddables.Credentials;
import cooksystem.server.entities.embaddables.Profile;
import cooksystem.server.entities.embaddables.UserState;
import cooksystem.server.exceptions.AuthenticationException;
import cooksystem.server.exceptions.NotFoundException;
import cooksystem.server.exceptions.BadRequestException;
import cooksystem.server.mappers.UserMapper;
import cooksystem.server.repositories.CompanyRepository;
import cooksystem.server.repositories.UserRepository;
import cooksystem.server.services.UserService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class UserServiceImplementation implements UserService {
    private final UserRepository userRepository;
    private final UserMapper userMapper;
    private final CompanyRepository companyRepository;

    /**
     * Returns a user by id (only for admins).
     */
    @Override
    public UserResponseDto getUser(Long id, Long userId) {
        findAdminUser(userId); // Validate requesting user is admin
        User targetUser = findUser(id);
        return userMapper.entityToDto(targetUser);
    }

    /**
     * Returns a list of all users (only for admins).
     */
    @Override
    public List<UserResponseDto> getAllUsers(Long userId) {
        findAdminUser(userId); // Validate requesting user is admin
        return userMapper.entitiesToDtos(userRepository.findAll());
    }

    /**
     * Create new user
     * Returns a user dto.
     */
    @Override
    public UserResponseDto createUser(UserRequestDto userRequestDto, Long companyId, Long userId) {
        findAdminUser(userId);

        // Validate required fields - is Admin defaults to false
        if (userRequestDto == null
                || userRequestDto.getProfile() == null
                || userRequestDto.getCredentials() == null
                || userRequestDto.getCredentials().getEmail() == null
                || userRequestDto.getCredentials().getPassword() == null) {
            throw new BadRequestException(
                    "Invalid user data",
                    "INVALID_REQUEST",
                    "First name, last name, email, password and phone are required"
            );
        }

        // Validate company exists
        var company = companyRepository.findById(companyId)
                .orElseThrow(() -> new NotFoundException(
                        "Company not found",
                        "COMPANY_NOT_FOUND",
                        "The company with ID " + companyId + " does not exist"
                ));

        // Create new user and set defaults
        User newUser = new User();

        // --- Profile ---
        Profile profile = new Profile();
        profile.setFirst(userRequestDto.getProfile().getFirst());
        profile.setLast(userRequestDto.getProfile().getLast());
        profile.setPhone(userRequestDto.getProfile().getPhone());
        newUser.setProfile(profile);

        // --- Credentials ---
        Credentials credentials = new Credentials();
        credentials.setEmail(userRequestDto.getCredentials().getEmail());

        // Use username from request (generated by frontend)
        credentials.setUsername(userRequestDto.getCredentials().getUsername());
        credentials.setPassword(userRequestDto.getCredentials().getPassword());
        newUser.setCredentials(credentials);

        // --- UserState ---
        UserState state = new UserState();
        state.setAdmin(userRequestDto.getUserState() != null
                && userRequestDto.getUserState().isAdmin());
        // active=false, status=PENDING by default
        newUser.setUserState(state);

        // --- Assign to Company ---
        newUser.getCompanies().add(company);

        // Save and return response
        User savedUser = userRepository.save(newUser);
        return userMapper.entityToDto(savedUser);

    }

    /**
     * Finds a user by ID or throws a NotFoundException.
     * id the ID of the user to find
     * the User entity if found
     */
    public User findUser(Long id) {
        return userRepository.findById(id)
                .orElseThrow(() -> new NotFoundException(
                        "Target user not found",
                        "USER_NOT_FOUND",
                        "The user with the given id does not exist"
                ));
    }

    /**
     * Returns a list of all users in a company (only for admins).
     */
    @Override
    public List<UserResponseDto> getUsersByCompany(Long companyId, Long userId) {
        // Validate admin user
        findAdminUser(userId);

        // Check if the company exists
        boolean companyExists = companyRepository.existsById(companyId);
        if (!companyExists) {
            throw new NotFoundException(
                    "Company not found",
                    "COMPANY_NOT_FOUND",
                    "The company with ID " + companyId + " does not exist"
            );
        }

        // Find all users in the given company
        List<User> users = userRepository.findByCompanies_Id(companyId);

        if (users.isEmpty()) {
            throw new NotFoundException(
                    "No users found for this company",
                    "NO_USERS_IN_COMPANY",
                    "The company with ID " + companyId + " has no registered users"
            );
        }

        return userMapper.entitiesToDtos(users);
    }

    /**
     * Helper method: finds the requesting user by ID and ensures they are an admin.
     * userId the ID of the requesting user (from session)
     */
    private void findAdminUser(Long userId) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new AuthenticationException(
                        "User not found",
                        "USER_NOT_FOUND",
                        "The requesting user does not exist"
                ));

        if (!user.getUserState().isAdmin()) {
            throw new AuthenticationException(
                    "Access denied",
                    "NOT_ADMIN",
                    "Only admins can perform this action"
            );
        }

        // TODO: return the user?
    }
}
