package cooksystem.server.mappers;

import cooksystem.server.dtos.UserRequestDto;
import cooksystem.server.dtos.UserResponseDto;
import cooksystem.server.entities.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring",
        uses = {ProfileMapper.class, CredentialsMapper.class, UserStateMapper.class})
public interface UserMapper {
    UserResponseDto entityToDto(User user);

    @Mapping(target = "id", ignore = true) // ignore Id generated by database
    User dtoToEntity(UserRequestDto userRequestDto);
    List<UserResponseDto> entitiesToDtos(List<User> users);
    List<User> dtosToEntities(List<UserRequestDto> userRequestDtos);
}
