package spring_boot.employee_management.service.impl;

import lombok.RequiredArgsConstructor;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;
import spring_boot.employee_management.dto.UserRegistrationDto;
import spring_boot.employee_management.model.Role;
import spring_boot.employee_management.model.User;
import spring_boot.employee_management.repository.UserRepository;
import spring_boot.employee_management.service.UserService;

import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Implementation of {@link UserService} that handles user registration
 * and authentication for Spring Security.
 *
 * <p>This class is annotated with {@link Service}, making it a Spring-managed
 * service component that can be injected into controllers or other beans.</p>
 *
 * <p>It uses {@link UserRepository} to access the database and
 * {@link BCryptPasswordEncoder} to securely hash user passwords.</p>
 */
@Service
@RequiredArgsConstructor
public class UserServiceImpl implements UserService {

    private final UserRepository userRepository;
    private final BCryptPasswordEncoder passwordEncoder;


    /**
     * Registers a new user based on the provided registration DTO.
     *
     * <p>This method:
     * <ol>
     *   <li>Builds a new {@link User} object from the DTO</li>
     *   <li>Encrypts the user's password using {@link BCryptPasswordEncoder}</li>
     *   <li>Assigns a default "ROLE_USER" to new users</li>
     *   <li>Saves the user into the database using {@link UserRepository}</li>
     * </ol>
     *
     * @param userRegistrationDto object containing user registration data from the client
     */
    @Override
    public void save(UserRegistrationDto userRegistrationDto) {
        User user = new User();

        // set user details for request payload
        // ignore id: generated by database
        user.setFirstName(userRegistrationDto.getFirstName());
        user.setLastName(userRegistrationDto.getLastName());
        user.setEmail(userRegistrationDto.getEmail());
        user.setPassword(passwordEncoder.encode(userRegistrationDto.getPassword()));

        // Assign Default role to user
        Role role = new Role();
        role.setName("ROLE_USER");
        user.setRoles(List.of(role));

        // persist data in database
        userRepository.save(user);
    }

    /**
     * Loads user-specific data used during authentication.
     *
     * <p>This method is required by Spring Security’s {@link org.springframework.security.core.userdetails.UserDetailsService}.
     * It retrieves a user by their email (used as the username) and wraps
     * them in a Spring Security {@link UserDetails} object, which holds
     * the user’s credentials and roles.</p>
     *
     * @param username the email or username entered during login
     * @return a {@link UserDetails} object recognized by Spring Security
     * @throws UsernameNotFoundException if no user exists with the given email
     */
    @Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
        User user = userRepository.findByEmail(username);
        if (user == null) {
            throw new UsernameNotFoundException("Invalid username or password.");
        }

        return new org.springframework.security.core.userdetails.User(
                user.getEmail(), user.getPassword(), mapRolesToAuthorities(user.getRoles()));
    }

    /**
     * Converts a collection of {@link Role} entities into a collection
     * of Spring Security {@link GrantedAuthority} objects.
     *
     * <p>Spring Security uses authorities to determine what permissions
     * or roles a user has during authentication and authorization.</p>
     *
     * @param roles the user’s assigned roles
     * @return a collection of granted authorities
     */
    private Collection<? extends GrantedAuthority> mapRolesToAuthorities(Collection<Role> roles){
        return roles.stream()
                .map(role -> new SimpleGrantedAuthority(role.getName()))
                .collect(Collectors.toList());
    }
}
